### ISSUE TITLE
Can't run the application

### ISSUE THREAD

**Issue by tonyhans7** [alexislepresle/gatsby-shopify-theme#7]
Create the app and install dependencies.

```
gatsby new gatsby-shopify-theme https://github.com/alexislepresle/gatsby-shopify-theme
npm install
gatsby develop
```
Run into graphql error. Using node v14.15.4. Any clue on how to fix this?

```
Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value: Date.'. Stacktrace was 'Error: Cannot create as TypeComposer the following
value: Date.
    at SchemaComposer.createTempTC (/Users/tony/Desktop/gatsby-shopify-theme/node_modules/graphql-compose/lib/SchemaComposer.js:365:11)
    at SchemaComposer.addAsComposer (/Users/tony/Desktop/gatsby-shopify-theme/node_modules/graphql-compose/lib/SchemaComposer.js:563:27)
    at createSchemaComposer (/Users/tony/Desktop/gatsby-shopify-theme/node_modules/gatsby/src/schema/schema-composer.js:16:18)
    at build (/Users/tony/Desktop/gatsby-shopify-theme/node_modules/gatsby/src/schema/index.js:104:26)
    at buildSchema (/Users/tony/Desktop/gatsby-shopify-theme/node_modules/gatsby/src/services/build-schema.ts:19:3)'
```

**Comment by CovetStudio** [comment]
I had the same issue. I removed node_modules and ran `yarn install`. That worked for me.

**Comment by tonyhans7** [comment]
Thanks @CovetStudio. It really works!

**Comment by alexislepresle** [comment]
Nice, can I close the issue @wphowto ?

**Comment by tonyhans7** [comment]
Sure. I close it now.
